DROP DATABASE IF EXISTS pokemon;
CREATE DATABASE pokemon;

USE pokemon;

SOURCE TRAINER.sql;
SOURCE TYPES.sql;
SOURCE SPECIES.sql;
SOURCE POKEMON.sql;
SOURCE FRIEND.sql;
SOURCE EVENT.sql;
SOURCE EGG.sql;
SOURCE LEVEL_UP.sql;
SOURCE MOVE.sql;
SOURCE MOVE_LEARNED.sql;