DROP DATABASE IF EXISTS pokemon;
CREATE DATABASE pokemon;

USE pokemon;

SOURCE TRAINER.sql;
SOURCE POKEMON.sql;
SOURCE FRIEND.sql;
SOURCE EVENT.sql;
SOURCE EGG.sql;
SOURCE LEVEL_UP.sql;
SOURCE MOVE.sql;